# Generated by Django 5.2 on 2025-06-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0002_remove_subject_course_alter_student_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='marks',
        ),
        migrations.AddField(
            model_name='marks',
            name='assignment_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='exam_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='Unnamed student', max_length=100),
        ),
    ]
