# Generated by Django 5.2 on 2025-06-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0004_remove_student_user_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
